---
apt_sources_list: >
  # Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources

apt_sources_remove: []
apt_sources_files: '{{ apt_sources_default |
  ansible.builtin.combine(apt_sources_override) }}'

apt_sources_default:
  ubuntu: |
    Types: deb
    URIs: http://archive.ubuntu.com/ubuntu/
    Suites: {{ ansible_distribution_release }} {{ ansible_distribution_release
      }}-updates {{ ansible_distribution_release }}-backports
    Components: main restricted universe multiverse
    Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

    Types: deb
    URIs: http://security.ubuntu.com/ubuntu/
    Suites: {{ ansible_distribution_release }}-security
    Components: main restricted universe multiverse
    Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

apt_sources_override: {}
...
