---
- name: Wait for connection
  hosts: all
  become: true
  gather_facts: false
  roles:
    - wait_connection

- name: Setup iSCSI target
  hosts: iscsi
  become: true
  gather_facts: false
  roles:
    - disk_label
    - target

- name: Setup iSCSI client
  hosts: gfs
  become: true
  gather_facts: false
  roles:
    - iscsi
...
