---
- name: Wait for connection
  hosts: all
  become: true
  gather_facts: false
  roles:
    - wait_connection
    - apt_sources
    - hosts
    - gen_keys

- name: Setup iSCSI target
  hosts: iscsi
  become: true
  gather_facts: false
  roles:
    - disk_label
    - target

- name: Setup GFS
  hosts: gfs
  become: true
  gather_facts: false
  roles:
    - iscsi
    - mpath
    - corosync
    - dlm
    - lvm
    - gfs2
    - pacemaker
...
