---
hosts_config: |
  {%
    set config = hosts_default |
      ansible.builtin.combine(hosts_override)
  %}
  {% for key, value in config.items() | sort(attribute=0) %}
  {{ '%-*s' | format(15, key) }} {{ value }}
  {% endfor %}
hosts_default:
  '127.0.0.1': localhost
  '::1': ip6-localhost ip6-loopback
  'fe00::0': ip6-localnet
  'ff00::0': ip6-mcastprefix
  'ff02::1': ip6-allnodes
  'ff02::2': ip6-allrouters
hosts_override: {}
...
