---
hosts_records:
  - key: '{{ ip_address }}'
    value: '{{ inventory_hostname }}'
hosts_override: '{{ groups["all"] | map("ansible.builtin.extract", hostvars,
  "hosts_records") | ansible.builtin.flatten | ansible.builtin.items2dict }}'
...
