---
corosync_authkey: '{{ undef(hint="corosync_authkey") }}'
corosync_cluster_name: '{{ undef(hint="corosync_cluster_name") }}'
corosync_cluster_uuid:
corosync_nodelist: {}
corosync_interfaces: []
corosync_rrp_mode: none
corosync_config: |
  totem {
    version: 2
    cluster_name: {{ corosync_cluster_name }}
    transport: knet
    crypto_cipher: aes256
    crypto_hash: sha256
    rrp_mode: {{ corosync_rrp_mode }}
  {% if corosync_cluster_uuid %}
    cluster_uuid: {{ corosync_cluster_uuid }}
  {% endif %}
  {% for iface in corosync_interfaces %}
    interface {
      linknumber: {{ loop.index0 }}
  {% for key, value in iface.items() %}
      {{ key }}: {{ value }}
  {% endfor %}
    }
  {% endfor %}
  }
  nodelist {
  {% for name, addrs in corosync_nodelist.items() %}
    node {
  {% for addr in addrs %}
      ring{{ loop.index0 }}_addr: {{ addr }}
  {% endfor %}
      name: {{ name }}
      nodeid: {{ loop.index }}
    }
  {% endfor %}
  }
  quorum {
    provider: corosync_votequorum
  }
  logging {
    to_logfile: yes
    logfile: /var/log/corosync/corosync.log
    to_syslog: yes
    timestamp: on
  }
...
