---
lvm_vgs:
  - vg: '{{ vg }}'
    pvs: ['{{ pv }}']
    opts:
      shared: true

lvm_lvs:
  - vg: '{{ vg }}'
    lv: '{{ lv }}'
    opts:
      extents: 100%VG

filesystem_devs:
  - dev: /dev/{{ vg }}/{{ lv }}
    fstype: gfs2
    opts: -O -j3 -p lock_dlm -t {{ corosync_cluster_name }}:gfs2
...
