---
pv: /dev/mapper/mpatha
vg: cluster_vg
lv: cluster_lv

lvm_lockd: true
lvm_global:
  locking_type: 1
  use_lvmlockd: 1
lvm_activate:
  - vg: '{{ vg }}'
    lv: '{{ lv }}'
    shared: true

gfs_mountpoint: /mnt/gfs2
directory_dirs:
  - path: '{{ gfs_mountpoint }}'
...
