---
iscsi_initiator_name: iqn.2025-03.ru.abegorov:gfs2:{{ inventory_hostname }}
iscsi_config_override:
  discovery.sendtargets.auth.username: '{{ target_discovery_userid }}'
  discovery.sendtargets.auth.password: '{{ target_discovery_password }}'
  discovery.sendtargets.auth.username_in: '{{
    target_discovery_mutual_userid }}'
  discovery.sendtargets.auth.password_in: '{{
    target_discovery_mutual_password }}'
  node.session.auth.username: '{{ target_node_acl.chap_userid }}'
  node.session.auth.password: '{{ target_node_acl.chap_password }}'
  node.session.auth.username_in: '{{ target_node_acl.chap_mutual_userid }}'
  node.session.auth.password_in: '{{ target_node_acl.chap_mutual_password }}'
iscsi_portals:
  - '{{ hostvars["iscsi-01"].ip_address_iscsi1 }}'
  - '{{ hostvars["iscsi-01"].ip_address_iscsi2 }}'
iscsi_targets:
  - target: '{{ hostvars["iscsi-01"].target_wwn }}'

mpath_reservation_key: '{{ lookup("ansible.builtin.password",
  "secrets/mpath_reservation_key_{{ inventory_hostname }}.txt",
  chars="01234567890abcdef", length=16) }}'
mpath_defaults_override:
  reservation_key: 0x{{ mpath_reservation_key }}

target_node_acl:
  chap_userid: initiator
  chap_password: '{{ lookup("ansible.builtin.password",
    "secrets/target_{{ inventory_hostname }}_password.txt", length=26) }}'
  chap_mutual_userid: initiator-mutual
  chap_mutual_password: '{{ lookup("ansible.builtin.password",
    "secrets/target_{{ inventory_hostname }}_mutual_password.txt",
    length=26) }}'
  mapped_luns:
    - alias: '{{ lookup("ansible.builtin.password",
        "secrets/target_{{ inventory_hostname }}_tpg1_lun1.txt",
        chars="01234567890abcdef", length=10) }}'
  node_wwn: '{{ iscsi_initiator_name }}'
...
